version: '3.8'

services:
  # n8n - Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: chatbot_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=https://n8n-dev.tenzaitech.online/
      - GENERIC_TIMEZONE=Asia/Bangkok
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./workflows:/home/node/workflows