@echo off
echo 🛒 Starting Tenzai Order Service...
cd order-service
echo Installing dependencies...
pip install -r requirements.txt >nul 2>&1
echo Starting service...
python -m uvicorn main:app --reload --port 8002